export type PostType = {
    id:number,
    title:string,
    description:string,
    file:string,
    createdAt:Date,
    updateAt:Date,
    isLiked:boolean,
    isOwner:boolean,
    isBookmark:boolean,
    likeCount:number,
    commentCount:number,
    user:{
        id:number,
        isFollowed:boolean,
        name:string,
        profileImage:string
    }
}